In [1]:
import pandas as pd

In [6]:
dat = pd.read_csv('complete.csv'); dat

,Id,Label,timeset,componentnumber,strongcompnum,indegree,outdegree,Degree,weighted indegree,weighted outdegree,...,Eccentricity,closnesscentrality,harmonicclosnesscentrality,betweenesscentrality,Authority,Hub,pageranks,clustering,eigencentrality,modularity_class
0,SteveSarian1,SteveSarian1,NaN,0,641,0,2,2,0,3,...,14,0.150768,0.185793,0.000000,0.000000,0.000287,0.000143,0.000000,0.000000,2
1,Bij88941056,Bij88941056,NaN,0,634,13,39,52,17,52,...,13,0.156791,0.211868,82495.852103,0.005718,0.059115,0.000645,0.008163,0.036033,2
2,lewinskylou2,lewinskylou2,NaN,0,307,7,1,8,7,1,...,1,1.000000,1.000000,1295.000000,0.006970,0.000160,0.000490,0.017857,0.015935,1
3,DerrickDuc,DerrickDuc,NaN,0,634,3,46,49,3,47,...,13,0.197248,0.272569,287509.160203,0.001838,0.000917,0.000238,0.000000,0.006941,2
4,Harm_Zwiers,Harm_Zwiers,NaN,0,634,2,4,6,3,5,...,22,0.072789,0.091677,5229.402660,0.000604,0.019240,0.000177,0.050000,0.011134,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3049,vossejongk,vossejongk,NaN,0,2578,0,2,2,0,2,...,1,1.000000,1.000000,0.000000,0.000000,0.006437,0.000143,0.000000,0.000000,1
3050,YvonnePtwit,YvonnePtwit,NaN,0,2579,0,2,2,0,2,...,2,0.750000,0.833333,0.000000,0.000000,0.030400,0.000143,0.500000,0.000000,1
3051,Paulien_2014,Paulien_2014,NaN,0,634,1,1,2,1,1,...,17,0.105911,0.126707,0.000000,0.000339,0.000405,0.000283,0.000000,0.008125,3
3052,robertwve,robertwve,NaN,0,2580,0,2,2,0,2,...,2,0.750000,0.833333,0.000000,0.000000,0.030400,0.000143,0.500000,0.000000,1
3053,HarriePetille,HarriePetille,NaN,0,2581,0,2,2,0,2,...,1,1.000000,1.000000,0.000000,0.000000,0.000499,0.000143,0.000000,0.000000,3

In [3]:
dat['componentnumber'].value_counts()

0    3054
Name: componentnumber, dtype: int64

In [5]:
dat['Id'].value_counts()

SteveSarian1      1
AsjeBello         1
PubliekeOmroep    1
dit_is_M          1
p0lic0rrupt       1
                 ..
EvaReports        1
TheDawn3121       1
cpt_caveman_nl    1
DuMonde88         1
HarriePetille     1
Name: Id, Length: 3054, dtype: int64